env:
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - promise
  - react
  - standard
extends:
  - plugin:react/recommended
  - standard
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - never
